/*
  contagem-objetos.sql
  Conta os objetos de usuario do banco - util para comparar antes/depois da recuperacao.
  Rode com: isql -q -user SYSDBA -password <senha> <banco> -i contagem-objetos.sql
*/
SET LIST ON;

SELECT COUNT(*) AS TABELAS
FROM RDB$RELATIONS
WHERE RDB$SYSTEM_FLAG = 0 AND RDB$VIEW_BLR IS NULL;

SELECT COUNT(*) AS VIEWS
FROM RDB$RELATIONS
WHERE RDB$SYSTEM_FLAG = 0 AND RDB$VIEW_BLR IS NOT NULL;

SELECT COUNT(*) AS PROCEDURES
FROM RDB$PROCEDURES;

SELECT COUNT(*) AS GENERATORS
FROM RDB$GENERATORS
WHERE RDB$SYSTEM_FLAG = 0;

SELECT COUNT(*) AS TRIGGERS
FROM RDB$TRIGGERS
WHERE RDB$SYSTEM_FLAG = 0;

SELECT COUNT(*) AS EXCEPTIONS
FROM RDB$EXCEPTIONS;

SELECT COUNT(*) AS INDICES_ATIVOS
FROM RDB$INDICES
WHERE RDB$SYSTEM_FLAG = 0 AND RDB$INDEX_INACTIVE = 0;

SELECT COUNT(*) AS INDICES_INACTIVE
FROM RDB$INDICES
WHERE RDB$SYSTEM_FLAG = 0 AND RDB$INDEX_INACTIVE = 1;

SELECT COUNT(*) AS UDFS
FROM RDB$FUNCTIONS
WHERE RDB$SYSTEM_FLAG = 0;
