/*
  contagem-objetos.sql
  Conta os objetos de usuario do banco - para comparar antes/depois da recuperacao.
  Uso: isql -q -user SYSDBA -password <senha> -i contagem-objetos.sql <banco>

  Indices: RDB$INDEX_INACTIVE NULL ou 0 = ativo; 1 = inativo; 3 = pendente
  (restore que quebrou em FK - procedure 05 secao 4b). Por isso o COALESCE.
  Esperado num banco pronto para producao: INDICES_INATIVOS = 0 e INDICES_PENDENTES = 0.
*/
SET LIST ON;

SELECT COUNT(*) AS TABELAS
FROM RDB$RELATIONS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0 AND RDB$VIEW_BLR IS NULL;

SELECT COUNT(*) AS VIEWS
FROM RDB$RELATIONS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0 AND RDB$VIEW_BLR IS NOT NULL;

SELECT COUNT(*) AS PROCEDURES
FROM RDB$PROCEDURES
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0;

SELECT COUNT(*) AS TRIGGERS
FROM RDB$TRIGGERS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0;

SELECT COUNT(*) AS TRIGGERS_INATIVOS
FROM RDB$TRIGGERS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0 AND RDB$TRIGGER_INACTIVE = 1;

SELECT COUNT(*) AS GENERATORS
FROM RDB$GENERATORS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0;

SELECT COUNT(*) AS EXCEPTIONS
FROM RDB$EXCEPTIONS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0;

SELECT COUNT(*) AS DOMINIOS
FROM RDB$FIELDS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0 AND RDB$FIELD_NAME NOT STARTING WITH 'RDB$';

SELECT COUNT(*) AS UDFS
FROM RDB$FUNCTIONS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0;

SELECT
  SUM(CASE WHEN C.RDB$CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 1 ELSE 0 END) AS PKS,
  SUM(CASE WHEN C.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 1 ELSE 0 END) AS FKS,
  SUM(CASE WHEN C.RDB$CONSTRAINT_TYPE = 'UNIQUE'      THEN 1 ELSE 0 END) AS UNIQUES,
  SUM(CASE WHEN C.RDB$CONSTRAINT_TYPE = 'CHECK'       THEN 1 ELSE 0 END) AS CHECKS
FROM RDB$RELATION_CONSTRAINTS C
JOIN RDB$RELATIONS R ON R.RDB$RELATION_NAME = C.RDB$RELATION_NAME
WHERE COALESCE(R.RDB$SYSTEM_FLAG, 0) = 0;

SELECT
  SUM(CASE WHEN COALESCE(RDB$INDEX_INACTIVE, 0) = 0 THEN 1 ELSE 0 END) AS INDICES_ATIVOS,
  SUM(CASE WHEN RDB$INDEX_INACTIVE = 1 THEN 1 ELSE 0 END)              AS INDICES_INATIVOS,
  SUM(CASE WHEN RDB$INDEX_INACTIVE = 3 THEN 1 ELSE 0 END)              AS INDICES_PENDENTES
FROM RDB$INDICES
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0;
