/*
  validar-fk-orfas.sql
  Gera consultas que detectam registros filhos sem pai (FK orfas).
  Util ANTES de ativar FKs apos restore com '-i' (procedure 05).

  Rode em duas etapas:
    1) Este script lista todas as FKs do banco.
    2) Para cada FK, gera uma consulta de validacao (proximo bloco).

  Saida do bloco 2 pode ser piped para outro isql para executar.
*/

/* === ETAPA 1: lista todas as FKs === */
SELECT
  TRIM(RC.RDB$CONSTRAINT_NAME)               AS NOME_FK,
  TRIM(RC.RDB$RELATION_NAME)                 AS TAB_FILHO,
  TRIM(IS_CHILD.RDB$FIELD_NAME)              AS COL_FILHO,
  TRIM(RC2.RDB$RELATION_NAME)                AS TAB_PAI,
  TRIM(IS_PARENT.RDB$FIELD_NAME)             AS COL_PAI
FROM RDB$RELATION_CONSTRAINTS RC
JOIN RDB$REF_CONSTRAINTS RF
  ON RF.RDB$CONSTRAINT_NAME = RC.RDB$CONSTRAINT_NAME
JOIN RDB$RELATION_CONSTRAINTS RC2
  ON RC2.RDB$CONSTRAINT_NAME = RF.RDB$CONST_NAME_UQ
JOIN RDB$INDEX_SEGMENTS IS_CHILD
  ON IS_CHILD.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
JOIN RDB$INDEX_SEGMENTS IS_PARENT
  ON IS_PARENT.RDB$INDEX_NAME = RC2.RDB$INDEX_NAME
 AND IS_PARENT.RDB$FIELD_POSITION = IS_CHILD.RDB$FIELD_POSITION
WHERE RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY 1;

/* === ETAPA 2: gera 'SELECT ...' para cada FK procurar orfas ===
   Saida pronta para piping em isql:
     isql ... -i orfas.sql > deteccao_orfas.sql
     isql ... -i deteccao_orfas.sql > resultado.txt
*/
SELECT
  'SELECT ''' || TRIM(RC.RDB$CONSTRAINT_NAME) || ''' AS FK, COUNT(*) AS ORFAS FROM "' ||
  TRIM(RC.RDB$RELATION_NAME) || '" F LEFT JOIN "' ||
  TRIM(RC2.RDB$RELATION_NAME) || '" P ON P."' ||
  TRIM(IS_PARENT.RDB$FIELD_NAME) || '" = F."' ||
  TRIM(IS_CHILD.RDB$FIELD_NAME) || '" WHERE F."' ||
  TRIM(IS_CHILD.RDB$FIELD_NAME) || '" IS NOT NULL AND P."' ||
  TRIM(IS_PARENT.RDB$FIELD_NAME) || '" IS NULL;' AS CONSULTA
FROM RDB$RELATION_CONSTRAINTS RC
JOIN RDB$REF_CONSTRAINTS RF
  ON RF.RDB$CONSTRAINT_NAME = RC.RDB$CONSTRAINT_NAME
JOIN RDB$RELATION_CONSTRAINTS RC2
  ON RC2.RDB$CONSTRAINT_NAME = RF.RDB$CONST_NAME_UQ
JOIN RDB$INDEX_SEGMENTS IS_CHILD
  ON IS_CHILD.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
JOIN RDB$INDEX_SEGMENTS IS_PARENT
  ON IS_PARENT.RDB$INDEX_NAME = RC2.RDB$INDEX_NAME
 AND IS_PARENT.RDB$FIELD_POSITION = IS_CHILD.RDB$FIELD_POSITION
WHERE RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY';
